name: GitHub Actions Demo

on:
  push:
    branches:
    - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
    - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        type: environment
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Output event name
        run: echo ${{ github.event_name }}
        
      - name: Output branch name
        run: echo ${{ github.ref }}
      
      - uses: actions/checkout@v4

      - name: List files in the repo
        run: tree

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    environment: Test
    if: github.event_name == "workflow_dispatch"
    steps:
      - run: echo "Testing..."

  load-test:
    name: Load-Test
    needs: build
    runs-on: ubuntu-latest
    environment: Load-Test
    if: github.event_name == "workflow_dispatch"
    steps:
      - run: echo "Testing..."
      - name: Sleep for 15 seconds
        run: sleep 15s
        shell: bash

  production:
    name: Production
    needs: [test, load-test]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.net
    if: inputs.environment == "Production"
    steps:
      - run: |
          echo "Step 1 deploying..."
          sleep 10
      - run: |
          echo "Step 2 deploying..."
          sleep 10
      - run: |
          echo "Step 3 deploying..."
          sleep 10
      - run: |
          echo "Step 4 deploying..."
          sleep 10
      - run: |
          echo "Step 5 deploying..."
          sleep 10
