name: GitHub Actions Demo

on:
  push:
    branches:
    - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
    - main
  schedule:
  - cron: "15 6 * * 0"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Output event name
        run: ${{ github.event_name }}
        
      - name: Output branch name
        run: ${{ github.ref }}
      
      - uses: actions/checkout@v4

      - name: List files in the repo
        run: tree
